const fs = require("fs");
const tmp = require("@swissquote/crafty-commons/packages/tmp");

/*

√: Yes
~: Maybe but not mandatory
X: Should not

| Item                        | IDE | Tool | jsLint |
| --------------------------- | --- | ---- | ------ |
| Read `crafty.config.js`     | √   | √    | X      |
| Use Crafty defaults         | √   | √    | X      |
| Extra presets from CLI      | X   | X    | √      |

*/

const ESLINT_PRESET_PATH = require.resolve("@swissquote/crafty-preset-eslint");
const CRAFTY_PATH = require.resolve("@swissquote/crafty");

/**
 * IDE Configuration generation.
 *
 * @param {Crafty} crafty
 * @returns
 */
function ideConfiguration(crafty) {
  const cliConfig = JSON.stringify(crafty.cliConfig, null, 2);

  return `// AUTOGENERATED BY CRAFTY - DO NOT EDIT
// This file helps IDEs autoconfigure themselves
// any change here will only be used by your IDE, not by Crafty

import { initialize } from "${CRAFTY_PATH}";
import { toESLintConfig } from "${ESLINT_PRESET_PATH}";

const crafty = await initialize(process.argv, {
  presets: [],
  readConfig: true,
});

const config = await toESLintConfig(crafty, {}, "ide");

export default config;
`;
}

/**
 * Configuration for other tools
 *
 * @param {Crafty} crafty
 * @returns
 */
function toolConfiguration(crafty) {
  const cliConfig = JSON.stringify(crafty.cliConfig, null, 2);

  return `// AUTOGENERATED BY CRAFTY - DO NOT EDIT

import { initialize } from "${CRAFTY_PATH}";
import { toESLintConfig } from "${ESLINT_PRESET_PATH}";

const crafty = await initialize(process.argv, ${cliConfig});

const config = await toESLintConfig(crafty, {});

export default config;
`;
}

/**
 * Configuration for jsLint/eslint command
 *
 * @returns
 */
function commandConfiguration(crafty, extraConfig) {
  const cliConfig = JSON.stringify(crafty.cliConfig, null, 2);

  return `// AUTOGENERATED BY CRAFTY - DO NOT EDIT
import { initialize } from "${CRAFTY_PATH}";
import { toESLintConfig } from "${ESLINT_PRESET_PATH}";

const crafty = await initialize([], ${cliConfig});

const extraConfig = ${JSON.stringify(extraConfig, null, 2)};

const config = await toESLintConfig(crafty, extraConfig, "jsLint");

export default config;
`;
}

function toTempFile(content) {
  const tmpfile = tmp.fileSync({ postfix: ".mjs" }).name;

  fs.writeFileSync(tmpfile, content);

  return tmpfile;
}

module.exports = {
  ideConfiguration,
  toolConfiguration,
  commandConfiguration,
  toTempFile
};
