// AUTOGENERATED BY CRAFTY - DO NOT EDIT
// This file helps IDEs autoconfigure themselves
// any change here will only be used by your IDE, not by Crafty

/* global process */
import { initialize } from "@swissquote/crafty";

const crafty = await initialize(process.argv);

const config = crafty.config.legacy_css
  ? crafty.config.stylelint_legacy
  : crafty.config.stylelint;
export default config;
