// AUTOGENERATED BY CRAFTY - DO NOT EDIT
// This file helps Crafty run Vitest with runtime configuration

/* global process */
import { initialize } from "@swissquote/crafty";
import { mergeConfig } from "vitest/config";
import { extractVitestCliState, loadNativeVitestConfig, materializeVitestOptions, normalizeVitestOptions } from "@swissquote/crafty-preset-vitest";

const crafty = await initialize(process.argv);

// Crafty configures its own environment for builds
// tests have different needs
process.env.NODE_ENV = "test";

const nativeConfig = await loadNativeVitestConfig();
const craftedConfig = materializeVitestOptions(
  normalizeVitestOptions(crafty, extractVitestCliState(process.argv.slice(2)))
);

export default mergeConfig(nativeConfig, craftedConfig);
