// This configuration was generated by Crafty
// This file is generated to improve IDE Integration
// You don't need to commit this file, nor need it to run `crafty build`

module.exports = {
    "plugins": [
        "/Users/onigoetz/Sites/Library/crafty/packages/stylelint-config-swissquote/index.js"
    ],
    "extends": [
        "/Users/onigoetz/Sites/Library/crafty/packages/stylelint-config-swissquote/recommended.js"
    ],
    "rules": {
        "swissquote/no-type-outside-scope": null
    }
};
