module.exports = {
  // Declares that this preset provides the "prettier" formatter. Crafty resolves
  // the active formatter from this (see Crafty#getActiveFormatter); when another
  // formatter (e.g. oxfmt) is active, Prettier's IDE config stands down so
  // editors use that formatter instead.
  provides: { formatter: "prettier" },
  defaultConfig() {
    return {
      prettier: {}
    };
  },
  ide(crafty) {
    if (!crafty.isActiveFormatter("prettier")) {
      return {};
    }

    return {
      "prettier.config.mjs": {
        shouldIgnore: false,
        alternativeFiles: ["prettier.config.js"],
        content: `// AUTOGENERATED BY CRAFTY - DO NOT EDIT
// This file helps IDEs autoconfigure themselves
// any change here will only be used by your IDE, not by Crafty

/* global process */
import { initialize } from "@swissquote/crafty";

const crafty = await initialize(process.argv);

const config = crafty.config.prettier;
export default config;
`
      }
    };
  }
};
