module.exports = {
  defaultConfig() {
    return {
      prettier: {}
    };
  },
  ide() {
    return {
      "prettier.config.mjs": {
        shouldIgnore: false,
        alternativeFiles: ["prettier.config.js"],
        content: `// AUTOGENERATED BY CRAFTY - DO NOT EDIT
// This file helps IDEs autoconfigure themselves
// any change here will only be used by your IDE, not by Crafty

/* global process */
import { initialize } from "@swissquote/crafty";

const crafty = await initialize(process.argv);

const config = crafty.config.prettier;
export default config;
`
      }
    };
  }
};
