// AUTOGENERATED BY CRAFTY - DO NOT EDIT
// This file helps IDEs autoconfigure themselves
// any change here will only be used by your IDE, not by Crafty

import { initialize } from "/Users/onigoetz/Sites/swissquote/crafty/packages/crafty/src/index.js";
import { toESLintConfig } from "/Users/onigoetz/Sites/swissquote/crafty/packages/crafty-preset-eslint/src/index.js";

const crafty = await initialize(process.argv, {
  "presets": [],
  "readConfig": true
});

const config = await toESLintConfig(crafty, {}, "ide");

export default config;
