const path = require("node:path");
const fs = require("node:fs");
const childProcess = require("child_process");

const {
  extractVitestCliState,
  materializeVitestOptions,
  serializeVitestOptions,
  normalizeVitestOptions
} = require("./configuration");

const RUNNER_BIN = path.join(__dirname, "run.js");
const IDE_CONFIG_FILE = "vitest.config.mjs";
const IDE_CONFIG_ALTERNATIVE_FILES = [
  "vitest.config.crafty.mjs",
  "vitest.config.js",
  "vitest.config.cjs",
  "vitest.config.mts",
  "vitest.config.ts",
  "vitest.config.cts"
];
const IDE_SETTINGS_FILE = ".vscode/settings.json";

function deleteOnExit(file) {
  process.addListener("exit", () => {
    try {
      if (fs.existsSync(file)) {
        fs.unlinkSync(file);
      }
    } catch (e) {
      console.error("Failed to delete ", file, e);
    }
  });
}

function createIdeConfigContent() {
  return `// AUTOGENERATED BY CRAFTY - DO NOT EDIT
// This file helps IDEs autoconfigure themselves

/* global process */
import { initialize } from "@swissquote/crafty";
import { extractVitestCliState, materializeVitestOptions, normalizeVitestOptions } from "@swissquote/crafty-preset-vitest";

const crafty = await initialize(process.argv);

// Crafty configures its own environment for builds
// tests have different needs
process.env.NODE_ENV = "test";

export default materializeVitestOptions(
  normalizeVitestOptions(crafty, extractVitestCliState(process.argv.slice(2)))
);
`;
}

function createIdeSettingsContent() {
  return `${JSON.stringify(
    { "vitest.rootConfig": IDE_CONFIG_FILE },
    null,
    2
  )}\n`;
}

function createTestRuntimeConfigContent(craftedConfigLiteral) {
  return `// AUTOGENERATED BY CRAFTY - DO NOT EDIT
// This file helps Crafty run Vitest with runtime configuration

import { materializeVitestOptions } from "@swissquote/crafty-preset-vitest";

export default materializeVitestOptions(${craftedConfigLiteral});
`;
}

module.exports = {
  extractVitestCliState,
  materializeVitestOptions,
  normalizeVitestOptions,
  ide(crafty) {
    return {
      [IDE_CONFIG_FILE]: {
        shouldIgnore: false,
        alternativeFiles: IDE_CONFIG_ALTERNATIVE_FILES,
        content: createIdeConfigContent()
      },
      [IDE_SETTINGS_FILE]: {
        shouldIgnore: false,
        mergeStrategy: "json",
        content: createIdeSettingsContent()
      }
    };
  },
  test(crafty, input, cli) {
    return new Promise((resolve, reject) => {
      const configFile = path.join(process.cwd(), "vitest-config-crafty.mjs");
      deleteOnExit(configFile);

      const cliState = extractVitestCliState(process.argv.slice(3));
      const craftedConfig = normalizeVitestOptions(crafty, cliState);

      fs.writeFileSync(
        configFile,
        createTestRuntimeConfigContent(
          JSON.stringify(serializeVitestOptions(craftedConfig), null, 2)
        )
      );

      const child = childProcess.spawn(
        process.argv[0],
        [RUNNER_BIN, ...cliState.runnerArgs, "--config", configFile],
        {
          cwd: process.cwd(),
          env: process.env,
          stdio: "inherit"
        }
      );

      child.on("error", reject);
      child.on("close", (code, signal) => {
        if (signal) {
          reject(
            new crafty.Information(
              `crafty test: Vitest terminated by signal ${signal}`
            )
          );
          return;
        }

        resolve(code);
      });
    });
  }
};
