// AUTOGENERATED BY CRAFTY - DO NOT EDIT
// This file helps IDEs autoconfigure themselves
// any change here will only be used by your IDE, not by Crafty

/* global process */

module.exports = (async () => {
  const { initialize } = await import("@swissquote/crafty");
  const { toESLintConfig } = await import("@swissquote/crafty-preset-eslint");
  
  const crafty = await initialize(process.argv, {
  "presets": [],
  "readConfig": true
});
  
  const config = await toESLintConfig(crafty, {}, "ide");
  
  return config;
})();
