// AUTOGENERATED BY CRAFTY - DO NOT EDIT
// This file helps IDEs autoconfigure themselves
// any change here will only be used by your IDE, not by Crafty

import { initialize } from "@swissquote/crafty";
import { toESLintConfig } from "@swissquote/crafty-preset-eslint";

const crafty = await initialize(process.argv, {
  "presets": [],
  "readConfig": true
});

const config = await toESLintConfig(crafty, {}, "ide");

export default config;
