import { createRequire } from "node:module";

import { toOxlintConfig } from "./oxlintConfigurator.js";
import { toTempConfigFile, ideConfiguration } from "./templates.js";
import OxlintCheckPlugin from "./OxlintCheckPlugin.js";

const require = createRequire(import.meta.url);

export default {
  toOxlintConfig,
  // Declares that this preset provides the "oxlint" linter. Crafty resolves the
  // active linter from this (see Crafty#getActiveLinter). The priority makes
  // oxlint win over ESLint when both are loaded (e.g. alongside a TypeScript
  // preset that pulls in ESLint), unless `linter` overrides it.
  provides: { linter: "oxlint", priority: 1 },
  presets: [require.resolve("@swissquote/crafty-preset-oxfmt")],
  ide(crafty) {
    if (!crafty.isActiveLinter("oxlint")) {
      return {};
    }

    return {
      ".oxlintrc.json": {
        shouldIgnore: false,
        // Remove the autogenerated ESLint config that this preset replaces
        alternativeFiles: ["eslint.config.mjs"],
        content: ideConfiguration(crafty)
      }
    };
  },
  commands() {
    return {
      oxlint: {
        async command(crafty) {
          (await import("./commands/oxLint.js")).default(crafty);
        },
        description: "Lint JavaScript and TypeScript with oxlint"
      }
    };
  },
  webpack(crafty, bundle, chain) {
    if (crafty.isWatching() || !crafty.isActiveLinter("oxlint")) {
      return;
    }

    chain
      .plugin("lint-oxlint")
      .use(OxlintCheckPlugin, [
        { config: toTempConfigFile(crafty, {}), includes: ["."] }
      ]);
  },
  rspack(crafty, bundle, chain) {
    if (crafty.isWatching() || !crafty.isActiveLinter("oxlint")) {
      return;
    }

    chain
      .plugin("lint-oxlint")
      .use(OxlintCheckPlugin, [
        { config: toTempConfigFile(crafty, {}), includes: ["."] }
      ]);
  }
};
