import OxfmtCheckPlugin from "./OxfmtCheckPlugin.js";

export default {
  // Declares that this preset provides the "oxfmt" formatter. Crafty resolves
  // the active formatter from this (see Crafty#getActiveFormatter). The priority
  // makes oxfmt win over Prettier when both are loaded (e.g. oxlint alongside a
  // TypeScript preset that pulls in Prettier), unless `formatter` overrides it.
  provides: { formatter: "oxfmt", priority: 1 },
  defaultConfig() {
    return {
      // oxfmt's defaults are Prettier-compatible, so an empty config is a
      // sensible starting point. Projects can add oxfmt options here.
      oxfmt: {}
    };
  },
  ide(crafty) {
    if (!crafty.isActiveFormatter("oxfmt")) {
      return {};
    }

    return {
      ".oxfmtrc.json": {
        shouldIgnore: false,
        // Remove the autogenerated Prettier config that this preset replaces
        // (user-authored .prettierrc files are intentionally left untouched).
        alternativeFiles: ["prettier.config.mjs"],
        content: `${JSON.stringify(crafty.config.oxfmt || {}, null, 2)}\n`
      }
    };
  },
  commands() {
    return {
      oxfmt: {
        async command(crafty) {
          (await import("./commands/oxfmt.js")).default(crafty);
        },
        description: "Format code with oxfmt"
      }
    };
  },
  webpack(crafty, bundle, chain) {
    if (crafty.isWatching() || !crafty.isActiveFormatter("oxfmt")) {
      return;
    }

    chain
      .plugin("format-oxfmt")
      .use(OxfmtCheckPlugin, [{ config: crafty.config.oxfmt }]);
  },
  rspack(crafty, bundle, chain) {
    if (crafty.isWatching() || !crafty.isActiveFormatter("oxfmt")) {
      return;
    }

    chain
      .plugin("format-oxfmt")
      .use(OxfmtCheckPlugin, [{ config: crafty.config.oxfmt }]);
  }
};
